settings:
  visible:
    menu_bar: false
    toolbar: true
    tray: true
    tab_headers: true
  server_is_remote: false
  remote_enable_importers: true
  context:
    notebook:
      max_height: 600px
toolbar:
  - g-data-tools
  - g-viewer-creator
  - g-subset-tools
tray:
  - g-subset-tools
  - g-gaussian-smooth
  - export
  - about
  - logger
