settings:
  visible:
    menu_bar: false
    toolbar: true
    tray: true
    tab_headers: true
  context:
    notebook:
      max_height: 600px
toolbar:
  - g-data-tools
  - g-viewer-creator
  - g-subset-tools
tray:
  - g-subset-plugin
  - g-gaussian-smooth
  - g-export-plot
